Traceback (most recent call last):
  File "/home/slawomir-tur/Documents/codecrafters-shell-python/app/main.py", line 89, in <module>
    main()
  File "/home/slawomir-tur/Documents/codecrafters-shell-python/app/main.py", line 75, in main
    if os.path.isfile(f"{path}/{args[0]}"):
                                ~~~~^^^
IndexError: list index out of range
